### ISSUE TITLE
Orange3-recommendation install in Anaconda environment

### ISSUE THREAD

**Issue by suebose012** [biolab/orange3-recommendation#4]
Hi, How can I install Orange3-recommendation add-in in the Anaconda environment? I have Windows10, 64-bit installation and Orange3.3. Instructions for a pip or conda install in the Anaconda environment would be a great help. I have managed to install other add-ins in Orange3. I don't see it in the documentation for this one. Thanks!

**Comment by kernc** [comment]
Since orange3-recommendation seems to not yet be released on PyPI (@salvacarrion, have you time to [check](https://packaging.python.org/distributing/#packaging-your-project) [this](https://packaging.python.org/distributing/#uploading-your-project-to-pypi)?), the following might work: 

``` bash
pip install git+https://github.com/biolab/orange3-recommendation.git
```

**Comment by suebose012** [comment]
@kernc  - Hi, Doesn't work.. here is what I get..
Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/biolab/orange3-recommendation.git C:\Users\SE...S~1\AppData\Local\Temp\pip-t7zsczz_-build
Cannot find command 'git'
I think I will wait for @salvacarrion to provide feedback, also have no need for a git+ install.
Thanks very much!

**Comment by salvacarrion** [comment]
It's already on PyPI. So in theory you should be able to install it now.

**Comment by suebose012** [comment]
@salvacarrion - Thank you salvacarrion and @kernc ! Closing this out, Pip installation from the PyPI link was successful:
> pip install  https://github.com/biolab/orange3-recommendation/tarball/0.1.3
Look forward to using this later in the week.
